import './globals.css';
import localFont from 'next/font/local'

import { Navbar } from '@/components/global/navbar';
import { config } from '@/utils/config';
import Footer from '@/components/global/footer/footer';

const cabinet = localFont({
  src: [
    {
      path: '../assets/CabinetGrotesk-Extralight.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../assets/CabinetGrotesk-Light.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../assets/CabinetGrotesk-Thin.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/CabinetGrotesk-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/CabinetGrotesk-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/CabinetGrotesk-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/CabinetGrotesk-Extrabold.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../assets/CabinetGrotesk-Black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
})

export const metadata = {
  title: config.name,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={cabinet.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
